config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'devise/confirmations' }
resources :foods
resources :recipes do
  resources :recipe_foods
end

devise_scope :user do
  get '/users/sign_out', to: 'devise/sessions#destroy'
  root to: 'devise/sessions#new'
end


# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.
# get "up" => "rails/health#show", as: :rails_health_check

# Defines the root path route ("/")
# root "posts#index"
get 'shopping_list/index', to: 'shopping_list#index', as: 'shopping_list_index'
get '/public_recipe', to: 'recipes#public_recipes'
resources :users
put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    redirect_to @recipe
  end

  def public_recipes
    @public = Recipe.includes(:user, :recipe_foods).where(public: true).order('created_at DESC')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="row mb-3">
      <%= form.label :name, "Recipe name", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <%= form.label :description, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <%= form.label :preparation_time, "Preparation time (in hour)", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :preparation_time, placeholder: "1.5", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <%= form.label :cooking_time, "Cooking time (in hour)", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :cooking_time, placeholder: "1", class: "form-control" %>
      </div>
    </div>
    <%= form.submit "Create recipe", class: "btn btn-primary" %>
  </form>
<% end %>

app/views/recipes/_header.html.erb
<div id="header">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/recipes">Recipe App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" aria-current="page" href="/recipes">Recipe list</a>
          <a class="nav-link" href="/foods">Food list</a>
          <a class="nav-link" href="/recipes">Public Recipe</a>
          <a class="nav-link" href="/users/sign_out">Sign out</a>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="card mb-3">
  <div class="card-body recipe_cont">
    <div class="recipe_name">
      <h3 class="card-title"><%= link_to recipe.name, recipe %></h3>
      <% if recipe.user_id == current_user.id %>
        <%= button_to "Remove", recipe, method: :delete, class: "btn btn-outline-danger" %>
      <% end %>
    </div>

    <div class="recipe_desc">
      <p class="card-text"><%= recipe.description %></p>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <h1 class="recipe_name">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Show this recipe", @recipe %> |
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">

  <div class="new_recipe_btn">
    <%= link_to "Add recipe", new_recipe_path, class: "btn btn-primary" %>
  </div>

  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <%= render recipe %>
    <% end %>
  </div>

</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1 class="recipe_name">Add new recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container">
  <% if @public && @public.length > 0 %>
    <div>
      <h1>Public Recipes</h1>
    </div>
    <table class="table table-striped">
      <tr>
        <th scope="col">Recipe Name</th>
        <th scope="col">By</th>
        <th scope="col">Total Food Items</th>
        <th scope="col">Total Price</th>
      </tr>
      <% @public.each do |recipe| %>
        <tr class="table-group-divider">
          <td>
            <%= link_to recipe.name, recipe_path(recipe) %>
          </td>
          <td>by: <%= recipe.user.name %></td>
          <td><%= recipe.recipe_foods.length %></td>
          <% total_price = recipe.recipe_foods.sum { |recipe_food| recipe_food.value(recipe_food.food_id, recipe_food.id) } %>
          <td>$<%= total_price %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h2>No Public Recipes in database</h2>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
<% if @recipe.public || (can?(:update, Recipe) && @recipe.user_id == current_user.id) %>
  <h1 class="recipe_name"><%= @recipe.name %></h1>

  <div class="recipe_detail_cont">
    <div class="recipe_time">
      <p class="recipe_preparation_time">
        Preparation time: 
          <% if @recipe.preparation_time %>
            <%= @recipe.preparation_time %> <%= @recipe.preparation_time > 1 ? "hours" : "hour" %>
          <% end %>
      </p>
      <p class="recipe_cooking_time">
        Cooking time: 
        <% if @recipe.preparation_time %>
          <%= @recipe.cooking_time %> <%= @recipe.cooking_time > 1 ? "hours" : "hour" %>
        <% end %>
      </p>

      <p class="recipe_steps">Steps go here...</p>
    </div>

    <div class="recipe_switch">
      <% if can? :update, @recipe %>
        <div class="public-button-container">
          <%= button_to(@recipe.public? ? "Make Private" : "Make Public", toggle_recipe_public_path(@recipe), method: :put) %>
        </div>
      <% end %>
      <% if can?(:update, Recipe) %>
        <%= form_with model: @recipe, id: "recipe_form", method: :patch do |f| %>
          <div class="form-check form-switch">
            <%= f.check_box :public, class: "form-check-input", id: "flexSwitchCheckChecked" %>
            <%= f.label :public, for: "flexSwitchCheckChecked", class: "form-check-label"  %>
          </div>

          <%= f.submit "Update Recipe", id: "submit_button", style: "display: none;" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="generate_btn">
    <% if @recipe.user_id == current_user.id %>
    <%= link_to 'Generate Shopping List', shopping_list_index_path(recipe_id: @recipe.id) %>
      <%= button_to "Add ingredient", new_recipe_recipe_food_path(@recipe), method: :get %>
    <% end %>
  </div>

  <div class="line"></div>

  <div class="recipe_foods">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @recipe_foods.each do |recipe_food| %>
          <%= render recipe_food %>
          <tr>
            <% if @recipe.id == recipe_food.recipe_id %>
              <th scope="row"><%= recipe_food.food.name %></th>
              <td><%= recipe_food.quantity %></td>
              <td>$<%= recipe_food.value(recipe_food.food_id, recipe_food.id) %></td>
              <td>
                <% if @recipe.user_id == current_user.id %>
                  <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food) %>
                  <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back to recipe list", recipes_path %>
  </div>

<% else %>
  <h2 class="recipe_name">This recipe is private</h2>
<% end %>
</div>