config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'devise/confirmations' }
resources :foods
resources :recipes do
  resources :recipe_foods
end

devise_scope :user do
  get '/users/sign_out', to: 'devise/sessions#destroy'
  root to: 'devise/sessions#new'
end


# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.
# get "up" => "rails/health#show", as: :rails_health_check

# Defines the root path route ("/")
# root "posts#index"
get 'shopping_list/index', to: 'shopping_list#index', as: 'shopping_list_index'
get '/public_recipe', to: 'recipes#public_recipes'
resources :users
put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy!

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <form>
      <div class="row mb-3">
        <%= form.label :name, "Food name", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>
      <fieldset class="row mb-3">
        <legend class="col-form-label col-sm-2 pt-0">Measurement unit</legend>
        <div class="col-sm-10">
          <div class="form-check">
            <%= form.radio_button :measurement_unit, "grams", class: "form-check-input" %>
            <%= form.label :measurement_unit, "grams", class: "form-check-label" %>
          </div>
          <div class="form-check">
            <%= form.radio_button :measurement_unit, "units", class: "form-check-input" %>
            <%= form.label :measurement_unit, "units", class: "form-check-label" %>
          </div>
        </div>
      </fieldset>
      <div class="row mb-3">
        <%= form.label :price, "Unit price ($)", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :price, placeholder: "15", class: "form-control" %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :quantity, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.number_field :quantity, placeholder: "5", class: "form-control" %>
        </div>
      </div>
      <%= form.submit class: "btn btn-primary" %>
    </form>
  </div>
<% end %>

app/views/foods/_header.html.erb
<div id="header">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/recipes">Recipe App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" aria-current="page" href="/recipes">Recipe list</a>
          <a class="nav-link" href="/foods">Food list</a>
          <a class="nav-link" href="/recipes">Public Recipe</a>
          <a class="nav-link" href="/users/sign_out">Sign out</a>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container">
  <div class="new_food_btn">
    <%= link_to "Add food", new_food_path, class: "btn btn-primary" %>
  </div>

  <div id="foods">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Measurement</th>
          <th scope="col">Unit price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @foods.each do |food| %>
          <%= render food %>
          <tr>
            <th scope="row"><%= link_to food.name, food %></th>
            <td><%= food.measurement_unit %></td>
            <td>$<%= food.price %></td>
            <td>
              <% if food.user_id == current_user.id %>
                <%= link_to "Delete", food, method: :delete %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container">
  <h1 class="food_name">New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="container">
  <%= render @food %>

  <div>
    <h1 class="food_name"><%= @food.name %></h1>
    <div class="food_price">
      <p>Measurement unit: <%= @food.measurement_unit %></p>
      <p>Unit price: $<%= @food.price %></p>
      <p>Quantity: <%= @food.quantity %></p>
    </div>

    <div class="update_food_btn">
      <% if @food.user_id == current_user.id %>
        <%= button_to "Delete", @food, method: :delete %>
      <% end %>
    </div>

    <%= link_to "Back to foods", foods_path %>
  </div>
</div>