config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'devise/confirmations' }
resources :foods
resources :recipes do
  resources :recipe_foods
end

devise_scope :user do
  get '/users/sign_out', to: 'devise/sessions#destroy'
  root to: 'devise/sessions#new'
end


# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.
# get "up" => "rails/health#show", as: :rails_health_check

# Defines the root path route ("/")
# root "posts#index"
get 'shopping_list/index', to: 'shopping_list#index', as: 'shopping_list_index'
get '/public_recipe', to: 'recipes#public_recipes'
resources :users
put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def value(food_id, recipe_food_id)
    unit_price = Food.find(food_id).price
    food_quantity = RecipeFood.find(recipe_food_id).quantity

    unit_price * food_quantity
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]
  before_action :set_recipe
  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = @recipe.recipe_foods.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to @recipe, notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to @recipe, notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy!

    respond_to do |format|
      format.html { redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id).merge(user_id: current_user.id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: [@recipe, recipe_food]) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

    <div>
    </div>

    <form class="row row-cols-lg-auto g-3 align-items-center">
      <div class="col-12">
        <%= form.select :food_id, options_for_select(Food.all.map { |food| ["#{food.name} (in #{food.measurement_unit})", food.id] }), { include_blank: 'Select food' }, { class: 'form-select' } %>
      </div>

      <div class="row mb-3 quantity_input">
        <%= form.label :quantity, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.number_field :quantity, placeholder: "12", class: "form-control" %>
        </div>
      </div>

      <div class="col-12">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </form>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
</div>

app/views/recipe_foods/edit.html.erb
<div class="container">
  <h1 class="recipe_name">Editing recipe food</h1>

  <%= render partial: "form", locals: { recipe: @recipe, recipe_food: @recipe_food } %>

  <br>

  <div>
    <%= link_to "Back to recipe detail", recipe_path(@recipe) %>
  </div>
</div>

app/views/recipe_foods/index.html.erb
<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="container">
  <h1 class="recipe_name">New recipe food</h1>

  <%= render partial: "form", locals: { recipe: @recipe, recipe_food: @recipe_food } %>

  <br>

  <div>
    <%= link_to "Back to the recipe", recipe_path(@recipe) %>
  </div>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>